name: OSX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  #OSX_ARCH: "arm64;x86_64"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "CodeBlocks - Unix Makefiles" #-DCMAKE_OSX_ARCHITECTURES=${{env.OSX_ARCH}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}} #/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: pwd & ls & ctest -C ${{env.BUILD_TYPE}}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ethertia-artifacts-darwin
        path: |
          run/bin/darwin-x64/Ethertia
          run/bin/darwin-x64/DedicatedServer
          run/bin/darwin-x64/libTwilightForest.dylib

